# Example of a local database setup.
login: &login
  host: localhost
  encoding: utf8
  adapter: postgresql
  username: loarie
  template: template_postgis

development:
  <<: *login
  database: ayp_development

test:
  <<: *login
  database: ayp_test

production:
  <<: *login
  database: ayp_production